# Use the language closest to rust, as rust itself is not supported
language: c

notifications:
  email:
    on_success: never
    on_failure: always

install:
  - sudo apt-get install nasm
  - curl https://static.rust-lang.org/rustup.sh | sudo sh -
  - ./downloadrustlibdir.sh
script:
  - make
