# Use the language closest to rust, as rust itself is not supported
language: c

notifications:
  email:
    on_success: never
    on_failure: always

before_install:
  - curl http://static.rust-lang.org/dist/rust-nightly-x86_64-unknown-linux-gnu.tar.gz | tar -xz
install:
  - sudo apt-get install nasm
  - sudo rust-nightly-x86_64-unknown-linux-gnu/install.sh
  - ./downloadrustlibdir.sh
script:
  - make
